---
title: "ARTICLES OF INCORPORATION"
subtitle: "Irenism, Inc."
format:
  pdf: default
---

FIRST: The undersigned, Martin Laptev, whose address is
12020 Amber Ridge Circle Apt 301, Germantown, MD 20876,
being at least eighteen (18) years of age, does hereby form a nonprofit,
nonstock corporation under and by virtue of the General Laws of the
State of Maryland authorizing the formation of corporations.

SECOND: The name of the corporation (hereinafter called the "Corporation") is:

Irenism, Inc.

THIRD: The Corporation is organized exclusively as a charitable and
educational organization within the meaning of section 501(c)(3) of the
Internal Revenue Code of 1986, as amended (or any corresponding
provisions of any future United States Internal Revenue law or
regulations thereunder, hereinafter collectively referred to as the
Internal Revenue Code), for the following purposes:

(a) to nurture physical, mental, and spiritual wellbeing through education and service;
(b) to promote the use of Dec, a decimal calendar and timekeeping system that measures years and/or days since midnight March 1st, 1 BC;
(c) to advance Deirenism, a religion which seeks to find common ground between rationalistic theology and other belief systems; and
(d) to engage in any other activities which are not inconsistent with Section 501(c)(3) of the Internal Revenue Code and applicable state law.

FOURTH: In order to carry out the purposes of the Corporation, the
Corporation shall have the following powers:

(a) to purchase, lease, receive by donation, acquire and operate real and personal property suitable or convenient for the purposes of the corporation;
(b) to solicit, receive and accept donations of money or property or any interest in property from any other entity or persons;
(c) to exercise any power, or engage in any function, incidental to accomplishing the nonprofit purposes of the Corporation provided or allowed by the General Laws of the State of Maryland, now or hereafter in force, to non-stock corporations, without limitation by the above description of specific powers.

FIFTH: The address of the principal office of the Corporation in this
state is: 12020 Amber Ridge Circle Apt 301, Germantown, MD 20876.

SIXTH: The Resident Agent of the Corporation is Martin Laptev, whose address
is 12020 Amber Ridge Circle Apt 301, Germantown, MD 20876.
The Resident Agent is a citizen of and resides in the
State of Maryland.

SEVENTH: The Corporation shall be governed by a Board of Directors. The
initial number of Directors of the Corporation shall be three (3). The
number of Directors may be increased or decreased in accordance with the
Bylaws of the Corporation but shall never be less than three (3). The
initial members of the Board of Directors, who shall serve until their
successors are elected and qualify, are as follows:

- Martin Laptev
- Irina Lapteva
- 

EIGHTH: The Corporation shall adopt bylaws which shall provide for:

(a) the number, qualification, election, classification, terms of office, powers and duties of the Board of Directors and for such committees as may be determined to be necessary or desirable,
(b) the qualification, rights, duties, and meetings of the members of the Corporation and for the quorum at such meetings;
(c) the selection of officers and their number, terms of office, rights, powers and duties; and
(d) for other matters relating to governance of the Corporation.

NINTH: The following provisions are hereby adopted to limit and regulate
the powers of the corporation and the Board of Directors.

(a) The corporation is not organized for pecuniary profit. No part of the net earnings of the Corporation shall inure to the benefit of or be distributable to its directors, officers, members or other private persons, except that the Corporation shall be authorized and empowered to pay reasonable compensation for services actually rendered and to make payments in furtherance of the purposes herein set forth;
(b) The corporation shall be non-profit and non-stock, and shall have no power to declare dividends. The corporation shall be composed of members. Qualifications for membership in the Corporation shall be defined in the Bylaws, but in no case shall membership be restricted on the basis of race, sex, ethnic origin or religious or political persuasion.
(c) The corporation shall conduct and direct its services and the use of its properties and facilities on the basis that the such services and uses are available regardless of race, sex, ethnic origin or religious or political persuasion.
(d) Except as provided in Sections 501(h) and 4911 of the Internal Revenue Code of 1986, as amended (or the corresponding provisions of any future United States Internal Revenue law) (hereafter the "Code"), no substantial part of the activities of the Corporation shall be the carrying on of propaganda or otherwise attempting to influence legislation. The Corporation shall not participate in nor intervene in (including the publishing or distribution of statements) any political campaign on behalf of any candidate for public office. Notwithstanding any other provisions, the Corporation shall not carry on any activity not permitted to be carried on by a Corporation exempt from federal income tax under Section 501(c)(3) of the Code or by a Corporation, contributions to which are deductible under Section 170(c)(2),
2055(a)(2) and 2522(a)(23) of the Code.
(e) If the Corporation is dissolved or ended for any reason, the Board of Directors shall dispose of all of the net assets of the Corporation exclusively to such organization(s) which are organized and operated exclusively for charitable or educational purposes as shall at the time qualify as an exempt organization under section 501(c)(3) of the Internal Revenue Code. Any remaining assets not disposed of by the Board shall be disposed of by the Court in the jurisdiction in which the principal office of the Corporation is then located, exclusively for such purposes or to such organizations.

TENTH: The duration and existence of the Corporation shall be perpetual.

ELEVENTH: The Corporation may indemnify any and all of its current and
future directors, officers, employees and agents as provided in the
Bylaws of the Corporation.

IN WITNESS WHEREOF, I, Martin Laptev, being more than 18 years of age and a citizen of the State
of Maryland, hereby consent to being designated in this document as Resident Agent for this corporation and have signed these Articles of Incorporation and acknowledged the same to be my own act on this 13th day of February 2024.

\

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\
Martin Laptev

Resident Agent
